"""Initial migration

Revision ID: e6c252ed6cae
Revises: 
Create Date: 2024-10-29 23:19:20.379747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e6c252ed6cae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan_group', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subscriber_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('net_fee', sa.Numeric(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_claim_number'), 'claim', ['claim_number'], unique=True)
    op.create_index(op.f('ix_claim_id'), 'claim', ['id'], unique=False)
    op.create_table('claimprocedure',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('service_date', sa.DateTime(), nullable=False),
    sa.Column('submitted_procedure', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quadrant', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_npi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_fees', sa.Numeric(), nullable=False),
    sa.Column('allowed_fees', sa.Numeric(), nullable=False),
    sa.Column('member_coinsurance', sa.Numeric(), nullable=False),
    sa.Column('member_copay', sa.Numeric(), nullable=False),
    sa.Column('net_fee', sa.Numeric(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claimprocedure_provider_npi'), 'claimprocedure', ['provider_npi'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claimprocedure_provider_npi'), table_name='claimprocedure')
    op.drop_table('claimprocedure')
    op.drop_index(op.f('ix_claim_id'), table_name='claim')
    op.drop_index(op.f('ix_claim_claim_number'), table_name='claim')
    op.drop_table('claim')
    # ### end Alembic commands ###
